////
This module included in the following assemblies:
-distr_tracing_otel/distr-tracing-otel-instrumentation.adoc
////
:_content-type: REFERENCE
[id="distr-tracing-config-otel-instrumentation_{context}"]
= OpenTelemetry Instrumentation configuration options

The {OTELName} can inject and configure OpenTelemetry auto-instrumentation libraries into your workloads. Currently, the project supports the injection of instrumentation libraries fro Go, Java, NodeJS, Python and ApacheHTTPD.

Auto-instrumentation in OpenTelemetry refers to the capability where the framework automatically instruments an application without manual code changes. This enables developers and Operators to get observability into their applications with minimal effort and changes to the existing codebase.

[IMPORTANT]
====
The {OTELName} Operator only supports the injection mechanism of the instrumentation libraries but does not support instrumentation libraries or upstream images. Customers can build their own instrumentation images or use community images.
====

== Instrumentation options

.Sample OpenTelemetry collector custom resource file
[source,yaml]
----
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  env:
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
  exporter:
    endpoint: http://production-collector.observability.svc.cluster.local:4317
  propagators:
    - w3c
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    env:
    - name: OTEL_JAVAAGENT_DEBUG
      value: "true"
----

.Parameters used by the Operator to define the Instrumentation
[cols=",,",options="header",]
|===
|Parameter |Description |Values

|env
|Common environment variables to define across all the instrumentations
|

|exporter
|Exporter defines exporter configuration
|

|propagators
|Propagators defines inter-process context propagation configuration
|`tracecontext`, `baggage`, `b3`, `b3multi`, `jaeger`, `ottrace`, `none`

|resource
|Resource attributes configuration
|

|sampler
|Sampling configuration
|

|apacheHttpd
|Configuration for the ApacheHTTPD instrumentation
|

|dotnet
|Configuration for the DotNet instrumentation
|

|go
|Configuration for the Golang instrumentation
|

|java
|Configuration for the Java instrumentation
|

|nodejs
|Configuration for the NodeJS instrumentation
|

|python
|Configuration for the Python instrumentation
|

|===

== Using the Instrumentation CR with Service Mesh

When using the Instrumentation CR with {SMProductName}, you must use the `b3multi` propagator.

=== Configure the Apache HTTPD auto-instrumentation

.Prameters for the `+.spec.apacheHttpd+` field
[cols=",,",options="header",]
|===
|Name |Description |Default

|attrs
|Apache HTTPD agent specific attributes
|

|configPath
|Location of Apache HTTPD server configuration
|/usr/local/apache2/conf

|env
|Apache HTTPD specific env vars
|

|image
|container image with Apache SDK and auto-instrumentation
|

|resourceRequirements
|the compute resource requirements
|

|version
|Apache HTTPD server version
|2.4

|===

To enable the injection, you need to provide the following annotation to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-apache-httpd: "true"
----

=== Configure the DotNet auto-instrumentation

[cols=",",options="header",]
|===

|Name
|Description

|env
|DotNet specific env vars

|image
|container image with DotNet SDK and auto-instrumentation

|resourceRequirements
|the compute resource requirements

|===

For DotNet auto-instrumentation, the OTEL_EXPORTER_OTLP_ENDPOINT environment variable is required to be set if the endpoint of the exporters is set to 4317. DotNet autoinstrumentation uses http/proto by default and the telemetry data needs to be setn to 4318 port.

To enable the injection, you need to provide the following annotation to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-dotnet: "true"
----

=== Configure the Golang auto-instrumentation

[cols=",",options="header",]
|===

|Name
|Description

|env
|Golang specific env vars

|image
|container image with Golang SDK and auto-instrumentation

|resourceRequirements
|the compute resource requirements

|===

To enable the injection, you need to provide the folllowing annotation to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-go: "true"
----

=== Configure the Java auto-instrumentation

[cols=",",options="header",]
|===

|Name
|Description

|env
|Java specific env vars

|image
|container image with Java SDK and auto-instrumentation

|resourceRequirements
|the compute resource requirements

|===

To enable the injection, you need to provide the following annotation to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-java: "true"
----

=== Configure the NodeJS auto-instrumentation

[cols=",",options="header",]
|===

|Name
|Description

|env
|NodeJS specific env vars

|image
|container image with NodeJS SDK and auto-instrumentation

|resourceRequirements
|the compute resource requirements

|===

To enable the injection, you need to provide the following annotations
to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-nodejs: "true"
instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/path/to/container/executable"
----

The `+instrumentation.opentelemetry.io/otel-go-auto-target-exe+`
annotation will set the value for the OTEL_GO_AUTO_TARGET_EXE
environment variable (which is required).

The Golang auto-instrumentation requires extra permissions to be provided in your OpenShift cluster:

[source,yaml]
----
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: otel-go-instrumentation-scc
allowHostDirVolumePlugin: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- "SYS_PTRACE"
fsGroup:
  type: RunAsAny
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
----

[source,terminal]
----
$ oc adm policy add-scc-to-user otel-go-instrumentation-scc -z <SERVICE_ACCOUNT>
----

=== Configure the Python auto-instrumentation

[cols=",",options="header",]
|===

|Name
|Description

|env
|Python specific env vars

|image
|container image with Python SDK and auto-instrumentation

|resourceRequirements
|the compute resource requirements

|===

For Python auto-instrumentation, the OTEL_EXPORTER_OTLP_ENDPOINT environment variable is required to be set if the endpoint of the exporters is set to 4317. Python autoinstrumentation uses http/proto by default and the telemetry data needs to be setn to 4318 port.

To enable the injection, you need to provide the following annotation to your PodSpec:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-python: "true"
----

=== Configure the OpenTelemetry SDK variables only

You can just configure the OpenTelemetry SDK variables in your pod using the following annotation:

[source,yaml]
----
instrumentation.opentelemetry.io/inject-sdk: "true"
----

Note that all the annotations can use these values:

* true: inject the `+Instrumentation+` resource from the namespace
* instrumentation-name: name of the Instrumentation resource to inject
from the current namespace
* other-namespace/instrumentation-name: name of the Instrumentation
resource to inject from other namespace
* false: do not inject any instrumentation

=== Multi-container pods

The instrumentation is performed on the first container available in the pod spec by default. In some cases, it becomes necessary to specify in
which container(s) this injection must be performed.

To do this, you need to specify the following annotation to your pod:

[source,yaml]
----
instrumentation.opentelemetry.io/container-names: "<container 1>,<container 2>"
----

Go auto-instrumentation doesn´t support multi-container
auto-instrumentation injection.
