// Module included in the following assemblies:
//
// * distr_tracing_tempo/distr-tracing-tempo-configuring.adoc

:_content-type: PROCEDURE
[id="distr-tracing-deploy-default-cli_{context}"]
= Deploying the {DTShortName} default strategy from the CLI

Follow this procedure to create an instance of {TempoShortName} from the command line.

.Prerequisites

* The {TempoOperator} has been installed and verified.
* You have reviewed the instructions for how to customize the deployment.
* You have access to the OpenShift CLI (`oc`) that matches your {product-title} version.
* You have access to the cluster as a user with the `cluster-admin` role.

.Procedure

. Log in to the {product-title} CLI as a user with the `cluster-admin` role.
+
[source,terminal]
----
$ oc login --username=<NAMEOFUSER> https://<HOSTNAME>:8443
----

. Create a new project named `tracing-system`.
+
[source,terminal]
----
$ oc new-project tracing-system
----

. Create a Secret YAML file to specify the secret for your object storage bucket. For instance, if you are using AWS S3, create a file that uses the `access_key_id` and `access_key_secret` fields to specify your AWS credentials and bucketnames, endpoint and region to define the object storage location. For example:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
stringData:
  endpoint: http://minio.minio.svc:9000
  bucket: tempo
  access_key_id: tempo
  access_key_secret: supersecret
type: Opaque
----

. Create a custom resource file named `tempo.yaml` that contains the following text:
+
.Example tempo-all-in-one.yaml
[source,yaml]
----
apiVersion: tempotracing.io/v1
kind: Tempo
metadata:
  name: example
----

. Run the following command to deploy {TempoShortName}:
+
[source,terminal]
----
$ oc create -n tracing-system -f tempo.yaml
----

. Run the following command to watch the progress of the pods during the installation process:
+
[source,terminal]
----
$ oc get pods -n tracing-system -w
----
+
After the installation process has completed, you should see output similar to the following example:
+
[source,terminal]
----
NAME                                         READY   STATUS    RESTARTS   AGE
tempo-all-in-one-inmemory-cdff7897b-qhfdx   2/2     Running   0          24s
----
