// Module included in the following assemblies:
//
// * distr-tracing-otel-migrating.adoc

:_content-type: PROCEDURE
[id="distr-tracing-otel-migrating-from-jaeger-with-sidecars_{context}"]
= (Temporary title) Migrating from the {JaegerName} to the {OTELName} with sidecars

The {OTELName} Operator can inject sidecars into Deployment workloads.

.Prerequisites

* The {JaegerName} is used on the cluster.
* {OTELName} is installed.

.Procedure

. Configure the OpenTelemetry Collector as a sidecar.
+
[source,yaml]
----
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: otel-collector-example
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors: [openshift]
        timeout: 2s
    exporters:
      otlp:
        endpoint: "tempo-<example>-gateway:8090" <1>
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [memory_limiter, resourcedetection, batch]
          exporters: [otlp]
----
<1> This endpoint points to the Gateway of a Tempo instance deployed by using the `<example>` Tempo Operator.

. Create a Service Account for running your application.
+
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sidecar
----

. Create a ClusterRole for the permissions needed by some processors.
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-sidecar
rules:
  <1>
- apiGroups: ["config.openshift.io"]
  resources: ["infrastructures", "infrastructures/status"]
  verbs: ["get", "watch", "list"]
----
<1> The `resourcedetectionprocessor` requires permissions for infrastructures and infrastructures/status.

. Create a ClusterRoleBinding to set the permissions for the Service Account.
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-sidecar
subjects:
- kind: ServiceAccount
  name: otel-collector-deployment
  namespace: otel-collector-example
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io
----

. Deploy the OpenTelemetry Collector as a sidecar.
+
[source,yaml]
----
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: otel-collector-example
spec:
  mode: sidecar
  serviceAccount: otel-collector-sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors: [openshift]
        timeout: 2s
    exporters:
      otlp:
        endpoint: "tempo-example-gateway:8090"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [memory_limiter, resourcedetection, batch]
          exporters: [otlp]
----

. Remove the injected Jaeger Agent from your application.
+
To remove the automatic sidecar injection from the Jaeger Operator, you need to remove the `"sidecar.jaegertracing.io/inject": "true"` annotation from your Deployment.

. Enable automatic injection of the OpenTelemetry sidecar.
+
To enable automatic injection of the OpenTelemetry sidecar, add the sidecar.opentelemetry.io/inject: "true" annotation to the .spec.template.metadata.annotations field of your Deployment.

. Use the created Service Account for your deployment
+
Use the Service Account we created before (otel-collector-sidecar) for the deployment of your application. This will allow the processors to get the correct information and add it to your traces.
