////
Module included in the following assemblies:
* service_mesh/v2x/servicemesh-release-notes.adoc
* distributed-tracing--release-notes.adoc
////
:_content-type: REFERENCE
[id="distr-tracing-rn-known-issues_{context}"]
= Known issues in the {DTProductName}

////
Consequence - What user action or situation would make this problem appear (Selecting the Foo option with the Bar version 1.3 plugin enabled results in an error message)? What did the customer experience as a result of the issue? What was the symptom?
Cause (if it has been identified) - Why did this happen?
Workaround (If there is one)- What can you do to avoid or negate the effects of this issue in the meantime? Sometimes if there is no workaround it is worthwhile telling readers to contact support for advice. Never promise future fixes.
Result - If the workaround does not completely address the problem.
////

== Known issues in the {DTProductName} 2.9

=== {JaegerName}

* Apache Spark is not supported.
ifndef::openshift-rosa[]

* The streaming deployment via AMQ/Kafka is unsupported on IBM Z and IBM Power Systems.
endif::openshift-rosa[]

=== {TempoName}

IMPORTANT: The {TempoName} is currently a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview].

* Currently, the custom TLS CA option is not implemented for connecting to object storage.
// link:https://issues.redhat.com/browse/TRACING-3462[TRACING-3462]

* Currently, when used with the {TempoOperator}, the Jaeger UI only displays services that have sent traces in the last 15 minutes. For services that did not send traces in the last 15 minutes, traces are still stored but not displayed in the Jaeger UI.
// link:https://issues.redhat.com/browse/TRACING-3139[TRACING-3139]

* Currently, the {TempoShortName} fails on the IBM Z (`s390x`) architecture.
// link:https://issues.redhat.com/browse/TRACING-3545[TRACING-3545]

* Currently, the Tempo query frontend service must not use internal mTLS when Gateway is not deployed. This issue does not affect the Jaeger Query API. The workaround is to disable mTLS.
+
.Workaround
:!example-caption:
====
Disable mTLS as follows:

. Open the {TempoOperator} ConfigMap for editing.
+
[source,console]
----
$ oc edit configmap tempo-operator-manager-config -n openshift-tempo-operator <1>
----
<1> The OpenShift project where the {TempoOperator} is installed.

. Disable the mTLS in the Operator configuration.
+
[source,yaml]
----
data:
  controller_manager_config.yaml: |
    featureGates:
      httpEncryption: false
      grpcEncryption: false
      builtInCertManagement:
        enabled: false
----

. Restart the {TempoOperator} Pod.
+
[source,console]
----
$ oc rollout restart deployment.apps/tempo-operator-controller -n openshift-tempo-operator
----
====
// link:https://issues.redhat.com/browse/TRACING-3510[TRACING-3510]

=== {OTELName}

IMPORTANT: The {OTELName} is currently a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview].

* Currently, you must manually set the link:https://operatorframework.io/operator-capabilities/[operator maturity] to Level IV, Deep Insights.
// link:https://issues.redhat.com/browse/TRACING-3431[TRACING-3431]

== Known issues in the previous releases of the {DTProductName}

* link:https://issues.redhat.com/browse/TRACING-2057[TRACING-2057] The Kafka API has been updated to `v1beta2` to support the Strimzi Kafka Operator 0.23.0. However, this API version is not supported by AMQ Streams 1.6.3. If you have the following environment, your Jaeger services will not be upgraded, and you cannot create new Jaeger services or modify existing Jaeger services:

** Jaeger Operator channel: *1.17.x stable* or *1.20.x stable*
** AMQ Streams Operator channel: *amq-streams-1.6.x*
+
To resolve this issue, switch the subscription channel for your AMQ Streams Operator to either *amq-streams-1.7.x* or *stable*.
