////
Module included in the following assemblies:
- distributed-tracing-release-notes.adoc
////
////
Feature – Describe the new functionality available to the customer. For enhancements, try to describe as specifically as possible where the customer will see changes.
Reason – If known, include why has the enhancement been implemented (use case, performance, technology, etc.). For example, showcases integration of X with Y, demonstrates Z API feature, includes latest framework bug fixes.
Result – If changed, describe the current user experience.
////
:_content-type: REFERENCE
[id="distr-tracing-rn-new-features_{context}"]
= New features and enhancements in the {DTProductName}

This release adds improvements related to the following components and concepts.

== New features and enhancements in the {DTProductName} 2.9

=== Component versions in the {DTProductName} 2.9

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.47.0

|{OTELName}
|OpenTelemetry
|0.81.0

|{TempoName}
|{TempoShortName}
|2.1.1
|===

=== {JaegerName}

* None.

=== {TempoName}

IMPORTANT: The {TempoName} is currently a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview].

This release introduces the following noteworthy enhancements for the {TempoShortName}:

* Support the link:https://operatorframework.io/operator-capabilities/[operator maturity] Level IV, Deep Insights, which enables upgrading, monitoring, and alerting of `TempoStack` instances and the {TempoOperator}.

* Add Ingress and OpenShift Route configuration for the Gateway.

* Support managed and unmanaged states in the `TempoStack` custom resource.

* Expose the following additional ingestion protocols in the Distributor service: Jaeger Thrift binary, Jaeger Thrift compact, Jaeger gRPC, and Zipkin. When the Gateway is enabled, only the OTLP gRPC is enabled.

* Expose the Jaeger Query gRPC endpoint on the Query Frontend service.

* Support multitenancy without Gateway authentication and authorization.

=== {OTELName}

IMPORTANT: The {OTELName} is currently a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview].

This release introduces the following noteworthy enhancements for the {OTELShortName}:

* Support OTLP metrics ingestion. The metrics can be forwarded and stored in the `user-workload-monitoring` via the Prometheus exporter.

* Support the link:https://operatorframework.io/operator-capabilities/[operator maturity] Level IV, Deep Insights, which enables upgrading and monitoring of `OpenTelemetry Collector` instances and the {OTELOperator}.

* Report traces and metrics from remote clusters using OTLP/HTTP(s).

* Collect OpenShift-specific resource attributes via the `resourcedetection` processor.

* Support managed and unmanaged states in the `OpenTelemetryCollector` custom resouce.

== New features and enhancements in the {DTProductName} 2.8

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.8

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.42

|{OTELName}
|OpenTelemetry
|0.74.0

|{TempoName}
|{TempoShortName}
|0.1.0
|===

== New features and enhancements in the {DTProductName} 2.7

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.7

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.39

|{OTELName}
|OpenTelemetry
|0.63.1
|===

== New features and enhancements in the {DTProductName} 2.6

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.6

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.38

|{OTELName}
|OpenTelemetry
|0.60
|===

== New features and enhancements in the {DTProductName} 2.5

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

This release introduces support for ingesting OpenTelemetry protocol (OTLP) to the {JaegerName} Operator.
The Operator now automatically enables the OTLP ports:

* Port 4317 is used for OTLP gRPC protocol.
* Port 4318 is used for OTLP HTTP protocol.

This release also adds support for collecting Kubernetes resource attributes to the {OTELName} Operator.

=== Component versions in the {DTProductName} 2.5

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.36

|{OTELName}
|OpenTelemetry
|0.56
|===

== New features and enhancements in the {DTProductName} 2.4

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

This release also adds support for auto-provisioning certificates using the Red Hat Elasticsearch Operator.

* Self-provisioning, which means using the {JaegerName} Operator to call the Red Hat Elasticsearch Operator during installation.
Self provisioning is fully supported with this release.
* Creating the Elasticsearch instance and certificates first and then configuring the {JaegerShortName} to use the certificate is a Technology Preview for this release.

[NOTE]
====
When upgrading to the {DTProductName} 2.4, the Operator recreates the Elasticsearch instance, which might take five to ten minutes.
Distributed tracing will be down and unavailable for that period.
====

=== Component versions in the {DTProductName} 2.4

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.34.1

|{OTELName}
|OpenTelemetry
|0.49
|===

== New features and enhancements in the {DTProductName} 2.3.1

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.3.1

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.30.2

|{OTELName}
|OpenTelemetry
|0.44.1-1
|===

== New features and enhancements in the {DTProductName} 2.3.0

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

With this release, the {JaegerName} Operator is now installed to the `openshift-distributed-tracing` namespace by default.
Before this update, the default installation had been in the `openshift-operators` namespace.

=== Component versions in the {DTProductName} 2.3.0

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.30.1

|{OTELName}
|OpenTelemetry
|0.44.0
|===

== New features and enhancements in the {DTProductName} 2.2.0

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.2.0

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.30.0

|{OTELName}
|OpenTelemetry
|0.42.0
|===

== New features and enhancements in the {DTProductName} 2.1.0

This release of the {DTProductName} addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.1.0

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.29.1

|{OTELName}
|OpenTelemetry
|0.41.1
|===

== New features and enhancements in the {DTProductName} 2.0.0

This release marks the rebranding of Red Hat OpenShift Jaeger to the {DTProductName}.
This release consists of the following changes, additions, and improvements:

* the {DTProductName} now consists of the following two main components:

** *{JaegerName}* - This component is based on the open source link:https://www.jaegertracing.io/[Jaeger project].

** *{OTELName}* - This component is based on the open source link:https://opentelemetry.io/[OpenTelemetry project].

* Updates {JaegerName} Operator to Jaeger 1.28. Going forward, the {DTProductName} will only support the `stable` Operator channel.
Channels for individual releases are no longer supported.

* Introduces a new {OTELName} Operator based on OpenTelemetry 0.33. Note that this Operator is a Technology Preview feature.

* Adds support for OpenTelemetry protocol (OTLP) to the Query service.

* Introduces a new distributed tracing icon that appears in the OpenShift OperatorHub.

* Includes rolling updates to the documentation to support the name change and new features.

This release also addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

=== Component versions in the {DTProductName} 2.0.0

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.28.0

|{OTELName}
|OpenTelemetry
|0.33.0
|===
