// Module included in the following assemblies:
//
// * /distr_tracing/distr_tracing_otel/distr-tracing-otel-using.adoc

:_content-type: PROCEDURE
[id="distr-tracing-otel-send-traces-and-metrics-to-otel-collector-with-sidecar_{context}"]
= Sending traces and metrics to the OpenTelemetry collector with sidecar injection

You can set up sending telemetry data to an OpenTelemetryCollector instance with sidecar injection.

The {OTELOperator} allows sidecar injection into Deployment workloads, automatically configuring your instrumentation to send telemetry data to the OpenTelemetry Collector.

.Prerequisites

* You have access to the cluster through the OpenShift web console or the OpenShift CLI (`oc`):

** You are logged in to the OpenShift web console as a cluster administrator with the `cluster-admin` role. For {product-dedicated}, you must have an account with the `dedicated-admin` role.

** An active OpenShift CLI (`oc`) session by a cluster administrator with the `cluster-admin` role.
+
[TIP]
====
* Ensure that your OpenShift CLI (`oc`) version is up to date and matches your {product-title} version.

* Run `oc login`:
+
[source,terminal]
----
$ oc login --username=<your_username>
----
====

.Procedure

. Create an OpenShift project for the OpenTelemtry Collector.
+
[source,yaml]
----
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: observability
----

. Create a ServiceAccount.
+
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sidecar
  namespace: observability
----

. Grant permissions to the ServiceAccount for the `k8sattributes` and `resourcedetection` processors.
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
- apiGroups: ["", "config.openshift.io"]
  resources: ["pods", "namespaces", "infrastructures", "infrastructures/status"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector-sidecar
  namespace: observability
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io
----

. Deploy the OpenTelemetry Collector as a sidecar.
+
[source,yaml]
----
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors: [openshift]
        timeout: 2s
    exporters:
      otlp:
        endpoint: "tempo-<example>-gateway:8090" <1>
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [memory_limiter, resourcedetection, batch]
          exporters: [otlp]
----
<1> This points to the Gateway of a Tempo instance deployed by using the `<example>` Tempo Operator.

. Create your Deployment using the `otel-collector-sidecar` ServiceAccount.

. Add the `sidecar.opentelemetry.io/inject: "true"` annotation to your deployment. This will inject all the needed environment variables to send data from your workloads to the OpenTelemetryCollector instance.
