// Module included in the following assemblies:
//
// * distr-tracing-tempo-configuring.adoc

:_content-type: PROCEDURE
[id="configuring-tempooperator-metrics-and-alerts_{context}"]
= Configuring {TempoOperator} metrics and alerts

Installing the {TempoOperator} by using the OpenShift web console provides the *Enable Operator recommended cluster monitoring on this Namespace* checkbox, which enables creating metrics and alerts of the {TempoOperator}.

If the checkbox was not selected during installation, you can manually enable metrics and alerts even after installing the {TempoOperator}.

.Procedure

* Add the `openshift.io/cluster-monitoring: "true"` label in the OpenShift project where the {TempoOperator} is installed, which is `openshift-tempo-operator` by default.

.Verification

. In the OpenShift web console, go to *Observe* -> *Targets*, filter for *Source: Platform*, and search for `tempo-operator`, which must have the *Up* status.

. To verify that alerts are set up correctly, go to *Observe* -> *Alerting* -> *Alerting rules*, filter for *Source: Platform*, and locate the *Alert rules* for the *{TempoOperator}*.
