// Module included in the following assemblies:
//
// * distr_tracing_tempo/distr-tracing-tempo-installing.adoc

:_content-type: PROCEDURE
[id="distr-tracing-tempo-accessing-tempo-console-cli_{context}"]
= Accessing the Tempo console from the CLI

The installation process creates a route to the Tempo console.

You can access the Tempo console by visiting its URL.

You can get the URL on the command line as follows.

.Prerequisites

* To access the Tempo console you must have either {SMProductName} or {DTProductName} installed, and {TempoName} installed, configured, and deployed.
* An active OpenShift CLI (`oc`) session by a cluster administrator with the `cluster-admin` role.
+
[TIP]
====
* Ensure that your OpenShift CLI (`oc`) version is up to date and matches your {product-title} version.

* Run `oc login`:
+
[source,terminal]
----
$ oc login --username=<your_username> 
----
====

.Procedure

. Query the route details:
+
[source,terminal]
----
$ export TEMPO_URL=$(oc get route -n <control_plane_namespace> tempo -o jsonpath='{.spec.host}')
----

. In a web browser, go to `\https://<route_from_previous_step>`.

. Log in using your cluster administrator credentials for the OpenShift web console.

. If you have added services to the service mesh and have generated traces, you can use the filters and *Find Traces* button to search your trace data.
+
NOTE: If you are validating the console installation, there is no trace data to display.
