// Module included in the following assemblies:
//
// * distr_tracing_tempo/distr-tracing-tempo-installing.adoc

:_content-type: PROCEDURE
[id="distr-tracing-tempo-accessing-tempo-console-web-console_{context}"]
= Accessing the Tempo console from the OpenShift web console

The installation process creates a route to the Tempo console.

You can access the Tempo console by visiting its URL.

You can get the URL in the *Administrator* view of the OpenShift web console as follows.

.Prerequisites

* {SMProductName} or {DTProductName} is installed.
* The {TempoName} is installed, configured, and deployed.
* You are logged in to the OpenShift web console as a cluster administrator with the `cluster-admin` role. For {product-dedicated}, you must have an account with the `dedicated-admin` role.

.Procedure

. Go to *Networking* -> *Routes*.

. On the *Routes* page, select the control plane project from the *Namespace* menu.
+
TIP: You can filter to the *tempo* route.

. Select the *Location* route for the Tempo console.

. Select *Log In With OpenShift* to use your cluster administrator credentials for the OpenShift web console.

. If you have added services to the service mesh and have generated traces, you can use the filters and the *Find Traces* button to search your trace data.
+
NOTE: The Tempo console initially shows no trace data to display following the Tempo console installation.
