// Module included in the following assemblies:
//
// * distr-tracing-otel-migrating.adoc

:_content-type: PROCEDURE
[id="distr-tracing-otel-migrating-from-jaeger-without-sidecars_{context}"]
= Migrating from the {JaegerName} to the {OTELName} without sidecars

.Prerequisites

* Existing instrumentation of applications uses {JaegerName} for tracing.
* The {OTELName} is installed.

.Procedure

. Configure OpenTelemetry Collector deployment.

. Create the OpenShift project where the OpenTelemetry Collector will be deployed.
+
[source,yaml]
----
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: observability
----

. Create a Service Account for running the OpenTelemetry Collector instance.
+
[source,yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-deployment
  namespace: observability
----

. Create a ClusterRole for setting the required permissions for the processors.
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector
rules:
# Permissions for pods and namespaces resources are needed for the k8sattributesprocessor
# Permissions for infrastructures and infrastructures/status are needed for resourcedetectionprocessor
- apiGroups: ["", "config.openshift.io"]
  resources: ["pods", "namespaces", "infrastructures", "infrastructures/status"]
  verbs: ["get", "watch", "list"]
----

. Create a ClusterRoleBinding to set the permissions for the Service Account.
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector
subjects:
- kind: ServiceAccount
  name: otel-collector-deployment
  namespace: observability
roleRef:
  kind: ClusterRole
  name: otel-collector
  apiGroup: rbac.authorization.k8s.io
----

. Create the OpenTelemetry Collector instance.
+
NOTE: This collector will be exporting traces to a Tempo instance. You must create your Tempo instance using the Red Hat Tempo Operator and place here the correct endpoint.
+
----
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  mode: deployment
  serviceAccount: otel-collector-deployment
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
          thrift_binary:
          thrift_compact:
          thrift_http:
    processors:
      batch:
      k8sattributes:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors: [openshift]
    exporters:
      otlp:
        endpoint: "tempo-example-gateway:8090"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [memory_limiter, k8sattributes, resourcedetection, batch]
          exporters: [otlp]
----

. Point your tracing endpoint to the OpenTelemetry Operator.

. If you are exporting your traces directly from your application to Jaeger, you will need to change the API endpoint from the Jaeger endpoint to the OpenTelemetry Collector endpoint.
+
For example, if you are using Golang and exporting your traces using the jaegerexporter, you can be using something like this:
+
----
exp, err := jaeger.New(jaeger.WithCollectorEndpoint(jaeger.WithEndpoint(url)))
----
+
The URL must point to the OpenTelemetry Collector API endpoint.
