:_content-type: ASSEMBLY
[id="distributed-tracing-rn-2-8"]
= Release notes for {DTProductName} 2.8
include::_attributes/common-attributes.adoc[]
:context: distributed-tracing-rn-2-8

toc::[]

include::modules/distr-tracing-product-overview.adoc[leveloffset=+1]

== Component versions in the {DTProductName} 2.8

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.42

|{OTELName}
|OpenTelemetry
|0.74.0

|{TempoName}
|{TempoShortName}
|0.1.0
|===

== Technology Preview features

This release introduces support for {TempoName} as a link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview] feature for {DTProductName}.
The feature uses version 0.1.0 of {TempoName} and version 2.0.1 of the upstream {TempoShortName} components.

You can use {TempoName} to replace Jaeger so that you can use S3-compatible storage instead of ElasticSearch.
Most users who use {TempoName} instead of Jaeger will not notice any difference in functionality because {TempoShortName} supports the same ingestion and query protocols as Jaeger and uses the same user interface.

If you enable this Technology Preview feature, note the following limitations of the current implementation:

* {TempoName} currently does not support disconnected installations. (link:https://issues.redhat.com/browse/TRACING-3145[TRACING-3145])

* When you use the Jaeger user interface (UI) with {TempoName}, the Jaeger UI lists only services that have sent traces within the last 15 minutes. For services that have not sent traces within the last 15 minutes, those traces are still stored even though they are not visible in the Jaeger UI. (link:https://issues.redhat.com/browse/TRACING-3139[TRACING-3139])

Expanded support for the {TempoOperator} is planned for future releases of {DTProductName}.
Possible additional features might include support for TLS authentication, multitenancy, and multiple clusters.
For more information about the {TempoOperator}, see link:https://tempo-operator.netlify.app[the Tempo community documentation].

:FeatureName: The {TempoName}
include::snippets/technology-preview.adoc[leveloffset=+1]

== Bug fixes

This release addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

//== Known issues

include::modules/support.adoc[leveloffset=+1]

include::modules/making-open-source-more-inclusive.adoc[leveloffset=+1]
