:_content-type: ASSEMBLY
[id="distributed-tracing-rn-2-0"]
= Release notes for {DTProductName} 2.0
include::_attributes/common-attributes.adoc[]
:context: distributed-tracing-rn-2-0

toc::[]

include::modules/distr-tracing-product-overview.adoc[leveloffset=+1]

== Component versions in the {DTProductName} 2.0.0

[options="header"]
|===
|Operator |Component |Version
|{JaegerName}
|Jaeger
|1.28.0

|{OTELName}
|OpenTelemetry
|0.33.0
|===

== New features and enhancements

This release marks the rebranding of Red Hat OpenShift Jaeger to the {DTProductName}.
This release consists of the following changes, additions, and improvements:

* The {DTProductName} now consists of the following two main components:

** *{JaegerName}* - This component is based on the open source link:https://www.jaegertracing.io/[Jaeger project].

** *{OTELName}* - This component is based on the open source link:https://opentelemetry.io/[OpenTelemetry project].

* Updates {JaegerName} Operator to Jaeger 1.28. Going forward, the {DTProductName} will only support the `stable` Operator channel.
Channels for individual releases are no longer supported.

* Introduces a new {OTELName} Operator based on OpenTelemetry 0.33. Note that this Operator is a Technology Preview feature.

* Adds support for OpenTelemetry protocol (OTLP) to the Query service.

* Introduces a new distributed tracing icon that appears in the OpenShift OperatorHub.

* Includes rolling updates to the documentation to support the name change and new features.

== Technology Preview features

This release includes the addition of the {OTELName}, which you install using the {OTELName} Operator. {OTELName} is based on the link:https://opentelemetry.io/[OpenTelemetry] APIs and instrumentation.

{OTELName} includes the OpenTelemetry Operator and Collector. The Collector can be used to receive traces in either the OpenTelemetry or Jaeger protocol and send the trace data to {DTProductName}. Other capabilities of the Collector are not supported at this time.

The OpenTelemetry Collector allows developers to instrument their code with vendor agnostic APIs, avoiding vendor lock-in and enabling a growing ecosystem of observability tooling.

== Bug fixes

This release also addresses Common Vulnerabilities and Exposures (CVEs) and bug fixes.

//== Known issues

include::modules/support.adoc[leveloffset=+1]

include::modules/making-open-source-more-inclusive.adoc[leveloffset=+1]
