:_content-type: ASSEMBLY
[id="dist-tracing-otel-migrating"]
= Migrating from the {JaegerName} to the {OTELShortName}
include::_attributes/common-attributes.adoc[]
:context: dist-tracing-otel-migrating

toc::[]

If you are already using Jaeger for distributed tracing of your applications, you can migrate to the {OTELShortName}, which is based on the link:opentelemetry.io/[OpenTelemetry] open-source project. The {OTELShortName} provides a set of APIs, libraries, agents, and instrumentation to facilitate observability in distributed systems. The OpenTelemetry Collector in the {OTELShortName} can ingest the Jaeger protocol, so you do not need to change the SDKs in your applications. Migration from the {JaegerName} to the {OTELShortName} requires configuring the OpenTelemetry Collector and your applications to report traces seamlessly. You can migrate sidecar and sidecarless deployments.

include::modules/distr-tracing-otel-migrating-from-jaeger-with-sidecars.adoc[leveloffset=+1]

include::modules/distr-tracing-otel-migrating-from-jaeger-without-sidecars.adoc[leveloffset=+1]
