:_mod-docs-content-type: ASSEMBLY
[id="otel-about"]
= About the {OTELShortName}
include::_attributes/common-attributes.adoc[]
:context: otel-about

toc::[]

OpenTelemetry is an observability framework and language-agnostic toolkit for instrumenting your applications and generating, collecting, processing, and exporting end-to-end telemetry data signals such as traces, metrics, and logs.

As an open standard and implementation that is widely adopted and has a significant contributing community that includes all major observability vendors and cloud providers, OpenTelemetry is vendor-agnostic and offers data portability and full control over your data.

The OpenTelemetry Collector allows you to use one binary for all of your collector needs rather than multiple different collectors from different vendors.

Collector receivers receive pulled or pushed data

Specification
  API (conventions+definitions), SDK(API+configuration), Data (data formats, protocols, semantic conventions)
{
Instrumentation libraries, auto or manual, that go within your code (single library per programming language)
v
Collector (single binary in multiple form factors to receive, process, and export data)
  pipeline(s)
    mention all types of possible pipeline components
v
Storage backend of a vendor of choice (because it is vendor-agnostic), e.g., to Tempo
}

OpenTelemetry offers the industry one common Specification and Semantic Conventions that define APIs, SDKs, and data attributes, allowing standardization across a codebase, libraries, and platforms.

OpenTelemetry provides a single set of APIs for telemetry data generation, encoding, and delivery, and a common OpenTelemetry Protocol (OTLP), which is implemented over the gRPC and HTTP transports. The gRPC is a modern open source high performance Remote Procedure Call (RPC) framework.

Collector https://youtu.be/N3bSvnpKiVE?t=2280
the same binary can be deployed near the application as an agent
or 
- Agent, local application or injesting data from another source
- Gateway, see https://youtu.be/N3bSvnpKiVE?t=2423

You can use the {OTELShortName} with an observability backend such as the Distributed tracing (Tempo) for tracing data storage and quering.




.Additional resources
* link:https://opentelemetry.io/docs/kubernetes/operator/[OpenTelemetry Operator for Kubernetes]
* link:https://opentelemetry.io/docs/collector/[OpenTelemetry Documentation: Collector]
* link:https://opentelemetry.io/docs/specs/otel/[OpenTelemetry Documentation: Specification]
* link:https://opentelemetry.io/docs/specs/otlp/[OpenTelemetry Documentation: OTLP Specification]
* link:https://opentelemetry.io/docs/languages/[OpenTelemetry Documentation: Language APIs & SDKs]
* link:https://opentelemetry.io/ecosystem/registry/[OpenTelemetry Documentation: Registry]
* link:https://grpc.io/[gRPC]


[id="otel-operator"]
== {OTELOperator}

The {OTELOperator} is based on the upstream OpenTelemetry Operator for Kubernetes.

The `OpenTelemetryCollector` object/CRD and `Instrumentation` object/CRD.

The Operator simplifies deployment of OpenTelemetry Collectors and reduces the effort to instrument your applications.

////

Red Hat offers cluster administrators and developers the Network Observability Operator to observe the network traffic for {product-title} clusters. The Network Observability Operator uses the eBPF technology to create network flows. The network flows are then enriched with {product-title} information. They are available as Prometheus metrics or as logs in Loki. You can view and analyze the stored network flows information in the {product-title} console for further insight and troubleshooting.

[id="dependency-network-observability"]
== Optional dependencies of the Network Observability Operator

* {loki-op}: Loki is the backend that can be used to store all collected flows with a maximal level of details. You can choose to use xref:../network_observability/installing-operators.adoc#network-observability-without-loki_network_observability[Network Observability without Loki], but there are some considerations for doing this, as described in the linked section. If you choose to install Loki, it is recommended to use the {loki-op}, which is supported by Red Hat.
* AMQ Streams Operator: Kafka provides scalability, resiliency and high availability in the {product-title} cluster for large scale deployments. If you choose to use Kafka, it is recommended to use the AMQ Streams Operator, because it is supported by Red Hat.

[id="network-observability-operator"]
== Network Observability Operator

The Network Observability Operator provides the Flow Collector API custom resource definition. A Flow Collector instance is a cluster-scoped resource that enables configuration of network flow collection. The Flow Collector instance deploys pods and services that form a monitoring pipeline where network flows are then collected and enriched with the Kubernetes metadata before storing in Loki or generating Prometheus metrics. The eBPF agent, which is deployed as a `daemonset` object, creates the network flows.

[id="no-console-integration"]
== {product-title} console integration

{product-title} console integration offers overview, topology view, and traffic flow tables in both *Administrator* and *Developer* perspectives.

In the *Administrator* perspective, you can find the Network Observability *Overview*, *Traffic flows*, and *Topology* views by clicking *Observe* -> *Network Traffic*. In the *Developer* perspective, you can view this information by clicking *Observe*. The Network Observability metrics dashboards in *Observe* -> *Dashboards* are only available to administrators. 

[NOTE]
====
To enable multi-tenancy for the developer perspective and for administrators with limited access to namespaces, you must specify permissions by defining roles. For more information, see xref:../../observability/network_observability/installing-operators.adoc#network-observability-multi-tenancy_network_observability[Enabling multi-tenancy in Network Observability].
====

[id="network-observability-dashboards"]
=== Network Observability metrics dashboards

On the *Overview* tab in the {product-title} console, you can view the overall aggregated metrics of the network traffic flow on the cluster. You can choose to display the information by zone, node, namespace, owner, pod, and service. Filters and display options can further refine the metrics. For more information, see xref:../network_observability/observing-network-traffic.adoc#network-observability-overview_nw-observe-network-traffic[Observing the network traffic from the Overview view].

In *Observe* -> *Dashboards*, the *Netobserv* dashboards provide a quick overview of the network flows in your {product-title} cluster. The *Netobserv/Health* dashboard provides metrics about the health of the Operator. For more information, see xref:../network_observability/metrics-alerts-dashboards.adoc#network-observability-metrics_metrics-dashboards-alerts[Network Observability Metrics] and xref:../network_observability/network-observability-operator-monitoring.adoc#network-observability-health-dashboard-overview_network_observability[Viewing health information].


[id="network-observability-topology-views"]
=== Network Observability topology views

The {product-title} console offers the *Topology* tab which displays a graphical representation of the network flows and the amount of traffic. The topology view represents traffic between the {product-title} components as a network graph. You can refine the graph by using the filters and display options. You can access the information for zone, node, namespace, owner, pod, and service.

[id="traffic-flow-tables"]
=== Traffic flow tables

The *Traffic flow* table view provides a view for raw flows, non aggregated filtering options, and configurable columns. The {product-title} console offers the *Traffic flows* tab which displays the data of the network flows and the amount of traffic.

[id="network-observability-cli"]
== Network Observability CLI
You can quickly debug and troubleshoot networking issues with Network Observability by using the Network Observability CLI (`oc netobserv`). The Network Observability CLI is a flow and packet visualization tool that relies on eBPF agents to stream collected data to an ephemeral collector pod. It requires no persistent storage during the capture. After the run, the output is transferred to your local machine. This enables quick, live insight into packets and flow data without installing the Network Observability Operator.

////
