:_mod-docs-content-type: ASSEMBLY
include::_attributes/common-attributes.adoc[]
[id="otel-release-notes"]
= Release notes for {OTELName}
:context: otel-release-notes

toc::[]

[id="otel-product-overview"]
== {OTELName} overview

{OTELName} is based on the open source link:https://opentelemetry.io/[OpenTelemetry project], which aims to provide unified, standardized, and vendor-neutral telemetry data collection for cloud-native software. {OTELName} product provides support for deploying and managing the OpenTelemetry Collector and simplifying the workload instrumentation.

The link:https://opentelemetry.io/docs/collector/[OpenTelemetry Collector] can receive, process, and forward telemetry data in multiple formats, making it the ideal component for telemetry processing and interoperability between telemetry systems. The Collector provides a unified solution for collecting and processing metrics, traces, and logs.

The OpenTelemetry Collector has a number of features including the following:

* Data Collection and Processing Hub:: It acts as a central component that gathers telemetry data like metrics and traces from various sources. This data can be created from instrumented applications and infrastructure.

* Customizable telemetry data pipeline:: The OpenTelemetry Collector is designed to be customizable. It supports various processors, exporters, and receivers.

* Auto-instrumentation features:: Automatic instrumentation simplifies the process of adding observability to applications. Developers don't need to manually instrument their code for basic telemetry data.

Here are some of the use cases for the OpenTelemetry Collector:

* Centralized data collection:: In a microservices architecture, the Collector can be deployed to aggregate data from multiple services.

* Data enrichment and processing:: Before forwarding data to analysis tools, the Collector can enrich, filter, and process this data.

* Multi-backend receiving and exporting:: The Collector can receive and send data to multiple monitoring and analysis platforms simultaneously.

[id="otel-3-0-rn"]
== {OTELName} {DTProductVersion}

{OTELName} {DTProductVersion} is based on link:https://opentelemetry.io/[OpenTelemetry] {OTELVersion}.

[id="new-features-and-enhancements_otel-3-0-rn"]
=== New features and enhancements

* The Operator "OpenShift distributed tracing data collection" was renamed to {OTELOperator}
* Support Prometheus receiver for metrics collection.
* Support Kafka receiver and exporter for sending traces and metrics to Kafka.
* Support cluster-wide proxy environments.
* The {OTELOperator} now creates Prometheus `ServiceMonitor` custom resource if Prometheus exporter is enabled.
* The operator now enables `Instrumentation` custom resource that allows injecting upstream OpenTelemetry auto-instrumentation libraries.
* ARM architecture is now supported.

[id="deprecations_otel-3-0-rn"]
=== Deprecations and breaking changes

* Jaeger exporter has been removed. Use OTLP exporter to send data to Jaeger collector.

[id="bug-fixes_otel-3-0-rn"]
=== Bug fixes

* Fixed support for disconnected environments via `oc adm catalog mirror`.

[id="known-issues_otel-3-0-rn"]
=== Known issues

* None.

include::modules/support.adoc[leveloffset=+1]

include::modules/making-open-source-more-inclusive.adoc[leveloffset=+1]
